import { escapeSqlString } from "../utils/escapeSql.js";
import { env } from "../config/env.js";
import { prisma } from "../lib/prisma.js";
import { log } from "../lib/logger.js";
import { Prisma, type SuiteSeverity } from "@prisma/client";

export interface TicketPayload {
  subject: string;
  description: string;
  priority: string;
  category: "bug";
  customerName: string;
  customerEmail: string;
}

export function suiteSeverityToPriority(severity: SuiteSeverity): string {
  const map: Record<SuiteSeverity, string> = {
    critical: "urgent",
    high: "high",
    medium: "medium",
    low: "low",
  };
  return map[severity] ?? "medium";
}

async function postQuery(sql: string, baseUrl: string): Promise<{ changes?: number; lastInsertRowid?: number; rows?: unknown[]; error?: string }> {
  const res = await fetch(`${baseUrl.replace(/\/$/, "")}/api/query`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ sql }),
  });
  const data = (await res.json()) as { changes?: number; lastInsertRowid?: number; rows?: unknown[]; error?: string };
  if (!res.ok) {
    throw new Error(data.error || res.statusText);
  }
  return data;
}

export async function createSupportTicket(payload: TicketPayload, baseUrl: string): Promise<number> {
  const s = escapeSqlString;
  const sql = `INSERT INTO sd_tickets (subject, description, status, priority, category, customer_name, customer_email) VALUES ('${s(payload.subject)}', '${s(payload.description)}', 'open', '${s(payload.priority)}', '${s(payload.category)}', '${s(payload.customerName)}', '${s(payload.customerEmail)}')`;
  const data = await postQuery(sql, baseUrl);
  const id = data.lastInsertRowid;
  if (id === undefined || Number.isNaN(Number(id))) {
    throw new Error("Support Desk did not return lastInsertRowid");
  }
  return Number(id);
}

export async function addTicketMessage(ticketId: number, content: string, baseUrl: string): Promise<void> {
  const sql = `INSERT INTO sd_messages (ticket_id, sender_type, sender_name, content) VALUES (${ticketId}, 'ai', 'TestHub-Bot', '${escapeSqlString(content)}')`;
  await postQuery(sql, baseUrl);
}

export function buildFailureDescription(ctx: {
  testName: string;
  errorMsg: string | null;
  suiteName: string;
  projectName: string;
  programName: string | null;
  environment: string;
  executedAt: string;
  durationMs: number | null;
  screenshotUrl: string | null;
  logUrl: string | null;
}): string {
  const lines = [
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "🔴 Test Failure Report — Auto-generated by TestHub",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    `📋 Test Suite:    ${ctx.suiteName}`,
    `📁 Project:       ${ctx.projectName}`,
    `🏢 Program:       ${ctx.programName ?? "—"}`,
    `🌐 Environment:   ${ctx.environment}`,
    `🕐 Executed At:   ${ctx.executedAt}`,
    `⏱️ Duration:      ${ctx.durationMs != null ? `${(ctx.durationMs / 1000).toFixed(1)}s` : "—"}`,
    "",
    `❌ Failed Test:    ${ctx.testName}`,
    `📝 Error:         ${ctx.errorMsg ?? "—"}`,
    `📎 Screenshot:    ${ctx.screenshotUrl ?? "—"}`,
    `📄 Full Log:      ${ctx.logUrl ?? "—"}`,
    "",
    "Steps to Reproduce: see test definition and CI artifacts.",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  ];
  return lines.join("\n");
}

async function getSupportDeskUrl(): Promise<string> {
  const row = await prisma.integrationSetting.findFirst({ orderBy: { updatedAt: "desc" } });
  return row?.supportDeskUrl?.trim() || env.SUPPORT_DESK_URL;
}

export async function supportDeskHealth(): Promise<boolean> {
  const url = await getSupportDeskUrl();
  try {
    const res = await fetch(`${url.replace(/\/$/, "")}/health`, { method: "GET" });
    return res.ok;
  } catch {
    return false;
  }
}

export async function processFailedTestResult(resultId: string): Promise<void> {
  const existing = await prisma.ticketBridgeLog.findUnique({ where: { resultId } });
  if (existing) return;

  const settings = await prisma.integrationSetting.findFirst({ orderBy: { updatedAt: "desc" } });
  if (settings && !settings.autoTicketGlobal) {
    log.info("Auto ticket globally disabled; skip bridge for", resultId);
    return;
  }

  const full = await prisma.testResult.findUnique({
    where: { id: resultId },
    include: {
      run: {
        include: {
          job: {
            include: {
              project: { include: { program: true } },
              suite: true,
            },
          },
        },
      },
    },
  });
  if (!full || full.status !== "fail") return;

  if (!full.run.job.project.autoCreateTickets) {
    log.info("Project auto_create_tickets false; skip", full.id);
    return;
  }

  const baseUrl = await getSupportDeskUrl();
  const priority = suiteSeverityToPriority(full.run.job.suite.severity);
  const subject = `[FAIL] ${full.testName} — ${full.run.job.project.name} ${full.run.job.project.environment}`;
  const description = buildFailureDescription({
    testName: full.testName,
    errorMsg: full.errorMsg,
    suiteName: full.run.job.suite.name,
    projectName: full.run.job.project.name,
    programName: full.run.job.project.program?.name ?? null,
    environment: full.run.job.project.environment,
    executedAt: full.createdAt.toISOString().replace("T", " ").slice(0, 19) + " UTC",
    durationMs: full.durationMs,
    screenshotUrl: full.screenshotUrl,
    logUrl: full.logUrl,
  });

  const payload: TicketPayload = {
    subject,
    description,
    priority,
    category: "bug",
    customerName: "TestHub-Automation",
    customerEmail: "testhub@xmachina.digital",
  };

  try {
    const ticketId = await createSupportTicket(payload, baseUrl);
    const messageBody =
      `Automated failure message for **${full.testName}**.\n\n` +
      (full.errorMsg ? `Error:\n${full.errorMsg}\n\n` : "") +
      (full.screenshotUrl ? `Screenshot: ${full.screenshotUrl}\n` : "") +
      (full.logUrl ? `Log: ${full.logUrl}` : "");
    await addTicketMessage(ticketId, messageBody, baseUrl);

    const integ = await prisma.integrationSetting.findFirst({ orderBy: { updatedAt: "desc" } });
    await prisma.ticketBridgeLog.create({
      data: {
        resultId: full.id,
        sdTicketId: ticketId,
        payloadJson: JSON.parse(JSON.stringify(payload)) as Prisma.InputJsonValue,
      },
    });
    if (integ) {
      await prisma.integrationSetting.update({
        where: { id: integ.id },
        data: {
          ticketsCreatedCount: { increment: 1 },
          lastHealthCheckOk: true,
          lastHealthCheckAt: new Date(),
        },
      });
    }
  } catch (e) {
    log.error("Integration bridge failed", e);
    const integ = await prisma.integrationSetting.findFirst({ orderBy: { updatedAt: "desc" } });
    if (integ) {
      await prisma.integrationSetting.update({
        where: { id: integ.id },
        data: { bridgeErrorCount: { increment: 1 }, lastHealthCheckOk: false, lastHealthCheckAt: new Date() },
      });
    }
    await prisma.bridgeRetryQueue.create({
      data: {
        payload: JSON.parse(JSON.stringify({ resultId: full.id, payload, error: String(e) })) as Prisma.InputJsonValue,
      },
    });
    throw e;
  }
}
